export const FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START';
export const FETCH_EMPLOYEES_SUCCEED = 'FETCH_EMPLOYEES_SUCCEED';
export const FETCH_EMPLOYEES_FAIL = 'FETCH_EMPLOYEES_FAIL';

export const TOGGLE_SELECT_COLUMNS = 'TOGGLE_SELECT_COLUMNS';
export const IMPORT_EMPLOYEES = 'IMPORT_EMPLOYEES';
export const DELETE_EMPLOYEES = 'DELETE_EMPLOYEES';

export const TOGGLE_SELECT_ONE_ROW = 'TOGGLE_SELECT_ONE_ROW';
export const TOGGLE_SELECT_ALL = 'TOGGLE_SELECT_ALL';

export const DOWNLOAD_EMPLOYEES_START = 'DOWNLOAD_EMPLOYEES_START';
export const DOWNLOAD_EMPLOYEES_SUCCEED = 'DOWNLOAD_EMPLOYEES_SUCCEED';
export const DOWNLOAD_EMPLOYEES_FAIL = 'DOWNLOAD_EMPLOYEES_FAIL';
