export const FETCH_EMPLOYEE_DETAIL_START = 'FETCH_EMPLOYEE_DETAIL_START';
export const FETCH_EMPLOYEE_DETAIL_SUCCEED = 'FETCH_EMPLOYEE_DETAIL_SUCCEED';
export const FETCH_EMPLOYEE_DETAIL_FAIL = 'FETCH_EMPLOYEE_DETAIL_FAIL';


